require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Thenewbostone' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-randombytes', :path => '../node_modules/react-native-randombytes'

  pod 'RNVirgilCrypto', :path => '../node_modules/react-native-virgil-crypto'

  target 'ThenewbostoneTests' do
    inherit! :complete
    # Pods for testing
    use_frameworks!
     pod 'VirgilCrypto', '~> 5.3.0'
     pod 'VirgilCryptoFoundation', '~> 0.12.0'
     pod 'VirgilCryptoPythia', '~> 0.12.0'
     $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
     'CocoaAsyncSocket', 'ComponentKit', 'DoubleConversion',
     'glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
     'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']
  
   pre_install do |installer|
     Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
     installer.pod_targets.each do |pod|
         if $static_framework.include?(pod.name)
           def pod.build_type;
             Pod::Target::BuildType.static_library
           end
         end
       end
    end

  end
 
   

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer) 
    end 
end
