name: Android

on: 
  push:
    branches:
      - development
      - master
  pull_request:
    - development
    - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - run: npm ci

    - run: ./gradlew assembleDebug -Dorg.gradle.logging.level=info
      working-directory: android
      name: Build Android apk (debug)
   
    - uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: '**/*.apk'
